### ISSUE TITLE
Templates is not working for  HAPI-FHIR Example Server with Azure SQL backend.

### ISSUE THREAD

**Issue by rameshkr1994** [hansenms/fhir-azure#1]
Dear @hansenms .

as i tried to add templates from below that is not working.

01       Vonk Server with Azure SQL backend.
02       HAPI-FHIR Example Server with Azure SQL backend.

is there any way to store fhir server data into sql server side or on-premise sql server for FHIR AZURE?

Please suggest me ...we want backend as sql server(on-premise).

Thanks
HadoopHelp

**Comment by hansenms** [comment]
This repo is no longer being maintained. You can deploy the Azure API for FHIR or the FHIR server for Azure.
